server:
  port: 8080
spring:
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      database: RestCloudAll
      port: 27017
      username: admin
      password: 123456
#  quartz config