server:
  port: 80
mongodb:
    usrname: admin
    password: 123456
    host: localhost
    port: 27017
    dbname: RestCloudAll
    authSource: admin
    authmechanism: SCRAM-SHA-1
spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.usrname}:${mongodb.password}@${mongodb.host}:${mongodb.port}/${mongodb.dbname}?authSource=${mongodb.authSource}&authMechanism=${mongodb.authmechanism}
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:mysql://192.168.31.221:3306/mybatis
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  quartz config